Repository openshift-kni/scheduler-plugins, pull requests merged in 2021-12, with the labels that each got.

#5 Ownership
  OWNERS
  OWNERS.upstream
  OWNERS_ALIASES
Labels: lgtm

#6 [KNI] fix repo's url in verify-commits.sh script
  .github/hooks/commit-msg
  hack/verify-commits.sh
Labels: approved

#11 [KNI] fix resync branch check
  hack-kni/verify-commits.sh
Labels: lgtm, approved

#15 [KNI] verify-commit: don't check resync branches
  .github/workflows/ci.yaml
  hack-kni/verify-commits.sh
Labels: lgtm, approved

#16 Resync partial 20211223 2
  RESYNC.md
  cloudbuild.yaml
  manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml
  pkg/coscheduling/core/core.go
  pkg/coscheduling/coscheduling.go
  pkg/coscheduling/coscheduling_test.go
  pkg/noderesourcetopology/README.md
Labels: lgtm, approved
