Repository openshift-kni/scheduler-plugins, pull requests merged in 2025-06, with the labels that each got.

#338 Resync 20250605 4.19 against release-1.31 u/s
  OWNERS
  README.md
  RESYNC.log.md
  RESYNC.md
  doc/install.md
  go.mod
  go.sum
  manifests/appgroup/deploy-sig-scheduling-controller-and-scheduler.yaml
  manifests/install/all-in-one.yaml
  manifests/install/charts/as-a-second-scheduler/Chart.yaml
  manifests/install/charts/as-a-second-scheduler/README.md
  manifests/install/charts/as-a-second-scheduler/values.yaml
  manifests/networktopology/deploy-sig-scheduling-controller-and-scheduler.yaml
  pkg/capacityscheduling/capacity_scheduling.go
  pkg/coscheduling/coscheduling.go
  pkg/networkaware/networkoverhead/networkoverhead.go
  pkg/networkaware/topologicalsort/topologicalsort.go
  pkg/sysched/sysched.go
  pkg/util/client_util.go
  site/content/en/_index.md
  site/content/en/docs/user-guide/installation.md
  site/content/en/docs/user-guide/installing-the-chart.md
  site/static/index.yaml
  test/integration/capacity_scheduling_test.go
  test/integration/coscheduling_test.go
  test/integration/elasticquota_controller_test.go
  test/integration/networkoverhead_test.go
  test/integration/podgroup_controller_test.go
  test/integration/sysched_test.go
  test/integration/topologicalsort_test.go
  test/util/fake.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
  vendor/k8s.io/code-generator/kube_codegen.sh
  vendor/k8s.io/component-base/metrics/prometheus/slis/routes.go
  vendor/k8s.io/csi-translation-lib/plugins/portworx.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/extender.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/fake_binder.go
  vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
  vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go
  vendor/k8s.io/kubernetes/pkg/scheduler/testing/wrappers.go
  vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/modules.txt
Labels: lgtm, approved

#330 [release-4.19]: Onboard noderesourcetopology scheduler to Konflux
  .konflux/DOWNSTREAM_OWNERS
  .tekton/DOWNSTREAM_OWNERS
  .tekton/noderesourcetopology-scheduler-4-19-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-19-push.yaml
  DOWNSTREAM_OWNERS_ALIASES
Labels: lgtm, approved

#331 [release-4.18]: Onboard noderesourcetopology scheduler to Konflux
  .konflux/DOWNSTREAM_OWNERS
  .tekton/DOWNSTREAM_OWNERS
  .tekton/noderesourcetopology-scheduler-4-18-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-18-push.yaml
  DOWNSTREAM_OWNERS_ALIASES
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved

#345 [release-4.12]: pin Dockerfile images
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved

#333 [release-4.16]: Onboard noderesourcetopology scheduler to Konflux
  .konflux/DOWNSTREAM_OWNERS
  .tekton/DOWNSTREAM_OWNERS
  .tekton/noderesourcetopology-scheduler-4-16-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-16-push.yaml
  DOWNSTREAM_OWNERS_ALIASES
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved

#335 [release-4.14]: Onboard noderesourcetopology scheduler to Konflux
  .konflux/DOWNSTREAM_OWNERS
  .tekton/DOWNSTREAM_OWNERS
  .tekton/noderesourcetopology-scheduler-4-14-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-14-push.yaml
  DOWNSTREAM_OWNERS_ALIASES
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved

#336 [release-4.13]: Onboard noderesourcetopology scheduler to Konflux
  .konflux/DOWNSTREAM_OWNERS
  .tekton/DOWNSTREAM_OWNERS
  .tekton/noderesourcetopology-scheduler-4-13-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-13-push.yaml
  DOWNSTREAM_OWNERS_ALIASES
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved

#341 pin Dockerfile images
  build/noderesourcetopology-plugin/konflux.Dockerfile
Labels: lgtm, approved, ok-to-test

#361 [KNI]: inject version for debug
  .tekton/build-pipeline.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#357 [release-4.18] [KNI][upstream] nrt: log: return updated generation value for cache
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
Labels: lgtm, approved

#352 [release-4.19] [KNI][upstream] nrt: log: return updated generation value for cache
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
Labels: lgtm, approved

#380 [release-4.17][KNI][upstream] nrt: log: introduce and use "generation" for cache
  RESYNC.log.md
  pkg/noderesourcetopology/cache/cache.go
  pkg/noderesourcetopology/cache/cache_test.go
  pkg/noderesourcetopology/cache/discardreserved.go
  pkg/noderesourcetopology/cache/discardreserved_test.go
  pkg/noderesourcetopology/cache/overreserve.go
  pkg/noderesourcetopology/cache/overreserve_test.go
  pkg/noderesourcetopology/cache/passthrough.go
  pkg/noderesourcetopology/filter.go
  pkg/noderesourcetopology/logging/logging.go
  pkg/noderesourcetopology/score.go
Labels: lgtm, approved

#383 [release-4.19][KNI] update resync log
  RESYNC.log.md
Labels: lgtm, approved

#374 [release-4.19]: Inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-19-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-19-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#376 [release-4.17]: Inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-17-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-17-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#375 [release-4.18]: Inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-18-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-18-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#377 [release-4.16]: inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-16-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-16-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#378 [release-4.14]: Inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-14-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-14-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#379 [release-4.15]: Inject version konflux builds
  .tekton/noderesourcetopology-scheduler-4-15-pull-request.yaml
  .tekton/noderesourcetopology-scheduler-4-15-push.yaml
  build/noderesourcetopology-plugin/konflux.Dockerfile
  cmd/noderesourcetopology-plugin/main.go
Labels: lgtm, approved

#388 [KNI] doc: add guidelines for branch-specific changes
  RESYNC.md
Labels: approved
